### ISSUE TITLE
新创建的用户通过 Python   create_engine 方式连接失败

### ISSUE THREAD

**Issue by wangjiancc** [taosdata/taosadapter#111]
TDEngine version: 3.0.1.5
新建用户， create_engine("taosrest://XXXXX")方式连接数据库，报没有权限，
root 用户能正常访问。

**Comment by sangshuduo** [comment]
谢谢，这个问题是 https://github.com/taosdata/taos-connector-python 的 bug

**Comment by wangjiancc** [comment]
谢谢！            REST方式已经可以了。原生连接的方式好像也有问题 create_engine("taos:
