### ISSUE TITLE
stmt 的close  没有回应

### ISSUE THREAD

**Issue by maikebing** [taosdata/taosadapter#129]
https://github.com/taosdata/taosadapter/blob/a2e99207d58c2d845f4af420ff2ef82b6540920c/controller/rest/stmt.go#L537 

没有类似下面的代码 响应 ws的请求。  

```
	resp := &StmtExecResp{
		Action:   STMTExec,
		ReqID:    req.ReqID,
		StmtID:   req.StmtID,
		Timing:   getDuration(ctx),
		Affected: affected,
	}
	wsWriteJson(session, resp)
``` 

postman 调试 流程 截图如下:
![1f5bb6b70ac79778054d904c8ad1427](https://user-images.githubusercontent.com/3445167/210214802-0414badc-1183-47d0-80af-3e87e275d5ce.png)

**Comment by maikebing** [comment]
schemaless_ws 的conn 也没回应 
https://github.com/taosdata/taosadapter/blob/a2e99207d58c2d845f4af420ff2ef82b6540920c/controller/rest/schemaless_ws.go#L83

**Comment by sangshuduo** [comment]
stmt close 后原 stmt id 即不可用，所以应用无需等待返回，可以认为 stmt close 永远都成功。另外 stmt close 不能调多次。

**Comment by maikebing** [comment]
总觉得不回复一下心里不踏实 那我就不等返回了吧。
