### ISSUE TITLE
taosadapter,启动rest 连接,数据库服务端出现停止现象,

### ISSUE THREAD

**Issue by w15135591069** [taosdata/taosadapter#180]

**Comment by sangshuduo** [comment]
版本？平台？复现步骤？

**Comment by w15135591069** [comment]
> 版本？平台？复现步骤？

版本:3.0.5.0
程序:jdk1.8,springboot,使用HikariDataSource连接池,jdbc:TAOS-RS,进行连接
未找到异常信息
怀疑执行 range('2023-08-03 00:00:00', '2023-08-03 23:59:59') every(10m) fill(value,0) 这类型的SQL语句失败后数据源服务器会写入大量的
![image](https://github.com/taosdata/taosadapter/assets/122333770/20537fde-2a8f-4b4b-b972-16b9c2348333)
core.pid文件,改文件大小4到4G左右

**Comment by sangshuduo** [comment]
> 

先升级到最新版本看还有没有这个问题

**Comment by sangshuduo** [comment]
另外如果是 taosd 的问题，这个 issue 应该提给 TDengine 仓库

**Comment by w15135591069** [comment]
ok,3qu

**Comment by w15135591069** [comment]
> 另外如果是 taosd 的问题，这个 issue 应该提给 TDengine 仓库

taosadapter 项目使用这种连接方式咱们服务端需要做啥特殊配置么?

**Comment by sangshuduo** [comment]
> > 另外如果是 taosd 的问题，这个 issue 应该提给 TDengine 仓库
> 
> taosadapter 项目使用这种连接方式咱们服务端需要做啥特殊配置么?

taosadapter 使用 native 接口连接 TDengine 服务端，和任何使用 native 接口连接服务端的应用没区别，默认使用 /etc/taos/taos.cfg 里的配置，也可以通过命令行或者环境变量的方式来配置，详细方法可以参考文档

**Comment by w15135591069** [comment]
同一个服务，6030和6041同时使用有影响么？

**Comment by w15135591069** [comment]
同一个服务，6030和6041同时使用有影响么？
