### ISSUE TITLE
Execute externally ?

### ISSUE THREAD

**Issue by perriea** [taosdata/taosadapter#23]
Hi !

Thanks for your work !
Is it possible to run the component outside the machine / container that runs **taosd** ? I'm asking this question because I'm using TDEngine with Kubernetes and I don't want to have two processes in the same container. 

It would be pretty cool if we could use the REST API as a scalable component with HPA. 

Thanks !

**Comment by sangshuduo** [comment]
Thanks for your question.

Yes, it's possible. You can run taosd and taosAdapter in two different pods and make sure the pod runs taosAdapter installed libtaos.so with the same version of the taosd. An easier way is to install the TDengine server standard package but don't run taosd but just run taosAdapter. And fill the taos client configuration file with your taosd's host. 

Please let us know what else we can help.

**Comment by sangshuduo** [comment]
Thanks for your question.

Yes, it's possible. You can run taosd and taosAdapter in two different pods and make sure the pod runs taosAdapter installed libtaos.so with the same version of the taosd. An easier way is to install the TDengine server standard package but don't run taosd but just run taosAdapter. And fill the taos client configuration file with your taosd's host. 

Please let us know what else we can help.

**Comment by perriea** [comment]
Very cool feature ! I have exactly your first case "taosd and taosAdapter in two different pods and make sure the pod runs taosAdapter installed libtaos.so with the same version of the taosd".

Last question : 
How target the cluster of TDengine with the adapter ? With `taos.cfg` or more configuration in  https://github.com/taosdata/taosadapter/blob/develop/example/config/taosadapter.toml ?

Thanks !

**Comment by sangshuduo** [comment]
> Very cool feature ! I have exactly your first case "taosd and taosAdapter in two different pods and make sure the pod runs taosAdapter installed libtaos.so with the same version of the taosd".
> 

Good to know your first case works.

> Last question : How target the TDengine cluster with the adapter ? With `taos.cfg` or more configuration in https://github.com/taosdata/taosadapter/blob/develop/example/config/taosadapter.toml ?
> 

Actually libtaos.so will always find taos.cfg from /etc/taos first. But you can also specify a different place by taosAdapter command line --taosConfigDir or put the location in the taosadapter.toml. Please notice the place is a directory name instead of the full path of taos.cfg file. taos.cfg uses firstEp and secondEp to connect the TDengine cluster.

> Thanks !

Good luck.

**Comment by perriea** [comment]
After hours of works 👍🏼 

Kubernetes : 
```
kubectl get sts,deploy,pod,hpa,cm -n common
NAME                                       READY   AGE
statefulset.apps/global-tdengine-cluster   3/3     28m

NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/global-adapter-tdengine-adapter      2/2     2            2           22m
deployment.apps/global-tdengine-cluster-arbitrator   1/1     1            1           28m

NAME                                                      READY   STATUS    RESTARTS   AGE
pod/global-adapter-tdengine-adapter-c7fbf7d4b-jl4wq       1/1     Running   0          20m
pod/global-adapter-tdengine-adapter-c7fbf7d4b-w4k2h       1/1     Running   0          12m
pod/global-tdengine-cluster-0                             1/1     Running   0          28m
pod/global-tdengine-cluster-1                             1/1     Running   0          28m
pod/global-tdengine-cluster-2                             1/1     Running   0          28m
pod/global-tdengine-cluster-arbitrator-5865ddb6fd-hv5d8   1/1     Running   0          28m

NAME                                                                  REFERENCE                                    TARGETS          MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/global-adapter-tdengine-adapter   Deployment/global-adapter-tdengine-adapter   8%/80%, 1%/80%   2         10        2          12m

NAME                                                DATA   AGE
configmap/global-adapter-tdengine-adapter-taoscfg   2      22m
configmap/global-tdengine-cluster-taoscfg           1      28m
```

Request on Adapter : 
```
curl --location --request POST 'http://root:taosdata@127.0.0.1:50094/rest/sql' --header 'Content-Type: application/json' --data-raw 'SHOW dnodes;'
{"status":"succ","head":["id","end_point","vnodes","cores","status","role","create_time","offline reason"],"column_meta":[["id",3,2],["end_point",8,134],["vnodes",3,2],["cores",3,2],["status",8,10],["role",8,5],["create_time",9,8],["offline reason",8,24]],"data":[[1,"global-tdengine-cluster-0.global-tdengine-cluster.common.svc.cluster.local:6030",0,3,"ready","any","2021-12-27 20:20:08.022",""],[2,"global-tdengine-cluster-1.global-tdengine-cluster.common.svc.cluster.local:6030",1,3,"ready","any","2021-12-27 20:20:31.521",""],[3,"global-tdengine-cluster-2.global-tdengine-cluster.common.svc.cluster.local:6030",0,3,"ready","any","2021-12-27 20:20:59.913",""],[0,"global-tdengine-cluster-arbitrator:6042",0,0,"ready","arb","2021-12-27 20:20:08.866","-"]],"rows":4}
```

During my tests, I observed that the adapter was based only on the service port of the TDEngine cluster. Is this really normal ? My configs applied : https://github.com/arktos-venture/helm-charts/tree/chart/tdengine-cluster/charts/tdengine-adapter/configs

I work on a Chart Helm & rootless images of TDEngine, are you interested ?
- https://github.com/arktos-venture/docker-tdengine
- https://github.com/arktos-venture/helm-charts/tree/chart/tdengine-cluster/charts

**Comment by sangshuduo** [comment]
> After hours of work 🥳
> 
> Kubernetes :
> 
> ```
> kubectl get sts,deploy,pod,hpa,cm -n common
> NAME                                       READY   AGE
> statefulset.apps/global-tdengine-cluster   3/3     28m
> 
> NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/global-adapter-tdengine-adapter      2/2     2            2           22m
> deployment.apps/global-tdengine-cluster-arbitrator   1/1     1            1           28m
> 
> NAME                                                      READY   STATUS    RESTARTS   AGE
> pod/global-adapter-tdengine-adapter-c7fbf7d4b-jl4wq       1/1     Running   0          20m
> pod/global-adapter-tdengine-adapter-c7fbf7d4b-w4k2h       1/1     Running   0          12m
> pod/global-tdengine-cluster-0                             1/1     Running   0          28m
> pod/global-tdengine-cluster-1                             1/1     Running   0          28m
> pod/global-tdengine-cluster-2                             1/1     Running   0          28m
> pod/global-tdengine-cluster-arbitrator-5865ddb6fd-hv5d8   1/1     Running   0          28m
> 
> NAME                                                                  REFERENCE                                    TARGETS          MINPODS   MAXPODS   REPLICAS   AGE
> horizontalpodautoscaler.autoscaling/global-adapter-tdengine-adapter   Deployment/global-adapter-tdengine-adapter   8%/80%, 1%/80%   2         10        2          12m
> 
> NAME                                                DATA   AGE
> configmap/global-adapter-tdengine-adapter-taoscfg   2      22m
> configmap/global-tdengine-cluster-taoscfg           1      28m
> ```
> 
> Request on Adapter :
> 
> ```
> curl --location --request POST 'http://root:taosdata@127.0.0.1:50094/rest/sql' --header 'Content-Type: application/json' --data-raw 'SHOW dnodes;'
> {"status":"succ","head":["id","end_point","vnodes","cores","status","role","create_time","offline reason"],"column_meta":[["id",3,2],["end_point",8,134],["vnodes",3,2],["cores",3,2],["status",8,10],["role",8,5],["create_time",9,8],["offline reason",8,24]],"data":[[1,"global-tdengine-cluster-0.global-tdengine-cluster.common.svc.cluster.local:6030",0,3,"ready","any","2021-12-27 20:20:08.022",""],[2,"global-tdengine-cluster-1.global-tdengine-cluster.common.svc.cluster.local:6030",1,3,"ready","any","2021-12-27 20:20:31.521",""],[3,"global-tdengine-cluster-2.global-tdengine-cluster.common.svc.cluster.local:6030",0,3,"ready","any","2021-12-27 20:20:59.913",""],[0,"global-tdengine-cluster-arbitrator:6042",0,0,"ready","arb","2021-12-27 20:20:08.866","-"]],"rows":4}
> ```
> 
> During my tests, I observed the adapter was based only on the service port of the TDEngine cluster. It's really normal ? My configs applied : https://github.com/arktos-venture/helm-charts/tree/release/charts/tdengine-adapter/configs
> 
> I work on a Chart Helm & rootless images of TDEngine, are you interested ?
> 
>     * https://github.com/arktos-venture/docker-tdengine/tree/release
> 
>     * https://github.com/arktos-venture/helm-charts/tree/release/charts
> 
> 
> It's based on https://github.com/taosdata/TDengine-Operator

Brilliant work! Would you like to contribute back to TDengine-Operator as a PR?

**Comment by perriea** [comment]
Yes, I prepare that ! Thanks for your help !
